[language-server.lsp-ai]
command = "lsp-ai"

[language-server.lsp-ai.config.memory]
file_store = {}

[language-server.lsp-ai.config.models.sonnet]
type = "anthropic"
chat_endpoint = "https://api.anthropic.com/v1/messages"
model = "claude-3-7-sonnet-latest"
auth_token_env_var_name = "ANTHROPIC_API_KEY"

[language-server.lsp-ai.config.models.haiku]
type = "anthropic"
chat_endpoint = "https://api.anthropic.com/v1/messages"
model = "claude-3-5-haiku-latest"
auth_token_env_var_name = "ANTHROPIC_API_KEY"

[[language-server.lsp-ai.config.actions]]
action_display_name = "Complete"
model = "haiku"
post_process = { extractor = "(?s)<answer>(.*?)</answer>" }

[language-server.lsp-ai.config.actions.parameters]
max_context = 4096
max_tokens = 4096
system = "You are an AI coding assistant. Your task is to explain code snippets. Follow these steps:\n\n1. Analyze the code context.\n2. Provide a clear, concise explanation of what the code does.\n3. Highlight any important patterns, potential issues, or best practices.\n4. Wrap your explanation in <explanation> tags.\n\nYour response should be informative yet concise, suitable for developers of various experience levels."

[[language-server.lsp-ai.config.actions.parameters.messages]]
role = "user"
content = "{CODE}"

[[language-server.lsp-ai.config.chat]]
trigger = "!C"
action_display_name = "Chat"
model = "sonnet"

[language-server.lsp-ai.config.chat.parameters]
max_context = 4096
max_tokens = 4096
system = "You are a code assistant chatbot. The user will ask you for assistance coding and you will do you best to answer succinctly and accurately"

[[language]]
name = "nix"
language-servers = ["nil", "lsp-ai"]
formatter = { command = "nixfmt" }
auto-format = true

[language-server.rust-analyzer.config]
cargo.features = "all"
# check.command = "clippy"

[[language]]
name = "rust"
language-servers = ["rust-analyzer", "lsp-ai"]
formatter = { command = "rustfmt", args = ["--edition", "2021"] }
auto-format = true

[[language]]
name = "markdown"
language-servers = ["marksman", "lsp-ai"]
formatter = { command = "dprint", args = ["fmt", "--stdin", "md"] }
auto-format = true

[[language]]
name = "bash"
language-servers = ["bash-language-server", "lsp-ai"]
auto-format = true

[[language]]
name = "toml"
language-servers = ["taplo", "lsp-ai"]
auto-format = true

[[language]]
name = "yaml"
language-servers = ["yaml-language-server", "lsp-ai"]
auto-format = true

[[language]]
name = "python"
language-servers = ["ruff", "pylsp", "lsp-ai"]
auto-format = true
